## <리스트3>

### 형성평가 1
- 리스트 내포를 이용하여 1번부터 입력받은 숫자까지의 숫자에 "No."를 붙인 문자열을 원소로 하는 리스트를 만들어 출력하시오.

> 리스트 내포(List Comprehension): 파이썬에서 for문과 if문을 한 라인에 작성하여 코드를 직관적으로 만들고, 실행속도를 높여주는 기법.

- 리스트 명 = [표현식 for 변수 in 반복 가능한 대상]

- 리스트 명 = [표현식 for 변수 in 반복 가능한 대상 if 조건문]
- 리스트 명 = [표현식 if 조건문 else 표현식 for 변수 in 반복 가능한 대상]

- 리스트 명 = [표현식 (바깥)for 변수 in 반복 가능한 대상 (안쪽)for 변수 in 반복 가능 대상]

In [17]:
result = ['No.%d' % (int(num)+1) for num in range(int(input()))] # (int(num)+1) 전체 관호 안해주면 자꾸 error뜸.
result

 5


['No.1', 'No.2', 'No.3', 'No.4', 'No.5']

### 형성평가 2
- 리스트의 크기와 정수를 입력 받아 다음 규칙을 만족하는 리스트를 리스트 내포를 이용하여 만들어 출력하시오. 
- **규칙: 인덱스가 입력받은 정수의 배수이면 True, 아니면 False**
- 0은 모든 정수의 배수이다.

In [21]:
li, num = input().split(' ')
result = [True if i%int(num)==0 else False for i in range(int(li))]
result

 11 3


[True, False, False, True, False, False, True, False, False, True, False]

### 형성평가 3
- 가람이는 주사위 놀이를 하다가 주사위를 10번 던져서 각 숫자가 몇 번씩 나왔는지 알아보려고 한다. 한번 던질 때마다 나온 주사위의 숫자를 입력받아서 숫자가 몇 번씩 나왔는지 출력하는 프로그램을 작성하시오. 

In [22]:
dice10 = input().split(' ')
num = 1
for i in range(6):
    a = dice10.count(str(num))
    print('%d : %d' % (num,a))
    num += 1

 5 6 3 4 5 5 2 2 4 6


1 : 0
2 : 2
3 : 1
4 : 2
5 : 3
6 : 2


### 형성평가 4
- 학생들의 점수를 입력받아서 입력받은 점수를 10점 단위로 구분하여 점수대 별 학생 수를 출력하는 프로그램을 작성하시오. (1명도 없는 점수는 출력하지 않는다.) 
- ***10으로 나눈 몫을 기준으로 리스트에 넣은 후 출력한다***

- for문으로 2차원 리스트 만들기
- https://dojang.io/mod/page/view.php?id=2293

In [ ]:
scores = input().split(' ')

for score in scores:
    

### 형성평가 5
- 10 미만의 자연수 두 개를 입력받아서 첫 번째 항과 두 번째 항을 입력받은 수로 초기화시킨 후 세번째 항부터는 전전항과 전항의 합을 구하여 그 합의 1의 자리로 채워서 차례로 10개를 출력하는 프로그램을 작성하시오. 

In [5]:
nums = list(map(int, input().split())) # 드디어 map 썼다!!!
while True:
    if nums[0] >= 10 or nums[1] >= 10 or len(nums) == 10:
        break
    result = nums[-1] + nums[-2]
    if result < 10:
        nums.append(result)
    else:
        n = result - 10 # 10으로 나눈 것도 됨! (result % 10)
        nums.append(n)
for i in nums:                 # print(*nums) 한줄이면 됨!
    print(i, end = ' ')

        

 3 5


3 5 8 3 1 4 5 9 4 3 

In [4]:
# 리스트 초기화, 몇개 생성
a = [] * 10
a

[]

### 형성평가 6
- 4행 3열의 리스트를 생성하여 아래와 같이 초기화한 후 차례대로 출력하고 마지막 줄에 배열의 모든 값을 더한 결과를 출력하는 프로그램을 작성하시오. 

In [14]:
l = [[3, 5, 9], 

    [2, 11, 5], 

    [8, 30, 10], 

    [22, 5, 1]] 

total_sum = 0

for a, b, c in l:    # 2차원 리스트 요소 출력 - for문 1번 사용 해서..
    print(a, b, c)
for i in l:
    total_i = sum(i) # list 안에 요소 다 더하기
    total_sum += total_i
    
print(total_sum)

3 5 9
2 11 5
8 30 10
22 5 1
111


In [18]:
# 2차원 리스트 요소 출력 - for문 2번 사용 해서..

l = [[3, 5, 9], 

    [2, 11, 5], 

    [8, 30, 10], 

    [22, 5, 1]] 

total_sum = 0
for i in l:
    total_i = sum(i) 
    total_sum += total_i
    for j in i:
        print(j, end = ' ')        # 여기 안에서 더해주면 합계 더 간단하게 sum 함수 안써도 구할 수 있음!
    print() # 얘가 행 구분해줌
print(total_sum)

3 5 9 
2 11 5 
8 30 10 
22 5 1 
111


- 예원언니꺼!!!!! numpy!!!!
- 리스트를 ndarray로 만드는거!!

### 형성평가 7
- 호석이네 학교는 6학년에 네 반이 있는데 각 반의 대표를 세 명씩 선발하여 제기차기 시합을 하였다. 반별로 세 명이 제기를 찬 개수를 입력받아 각 반별로 제기를 찬 개수의 합계를 출력하는 프로그램을 작성하시오.

In [26]:
# 변수 이름을 너무 대충 지었당...급하다 급해!!!

while True:
    scores_lst = []
    for i in range(4): # range(1,5) 로 했으면 i+=1 할필요 없었음!!!!!!!
        i += 1
        scores = list(map(int, input(f'{i}class? ').split()))
        sum_scores = sum(scores)                 # scores_lst.append(sum(scores)) 하면 한번에 됨!!!!!!!!!!!!
        scores_lst.append(sum_scores)
    for s in scores_lst:
        c =1
        print(f'{c}class : {s}')
        c += 1
       
    break

1class?  1 2 3
2class?  4 5 6
3class?  1 2 3
4class?  4 5 6


1class : 6
1class : 15
1class : 6
1class : 15


### 형성평가 8
- 2차원 리스트를 생성하여 1행의 1열과 3열, 5열을 각각 1로 나머지는 모두 0으로 초기화한 후 2행부
터는 바로 전행의 왼쪽과 오른쪽의 값을 더하여 채운 후 출력하는 프로그램을 작성하시오. 

In [ ]:
np.zeros((3,2)) # 0으로 채워진 3x2 크기 행렬

In [34]:
import numpy as np
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 형성평가 9
- 2행 3열 리스트 두 개에 각각의 값을 입력 받은 후 두 배열의 같은 위치끼리 곱하여 새로운 리스트에 저장한 후 출력하는 프로그램을 작성하시오. 

In [5]:
import numpy as np

print('first array')
lst1 = []
a1 = list(map(int, input().split()))
b1 = list(map(int, input().split()))
lst1.append(a1)
lst1.append(b1)
print('second array')
lst2 = []
a2 = list(map(int, input().split()))
b2 = list(map(int, input().split()))
lst2.append(a2)
lst2.append(b2)

result = np.multiply(lst1,lst2)     # numpy 썼다!!!!!!!!!!
# for i in result:
#     for j in i:
#         print(j, end = ' ')
#     print()

result

first array


 1 3 8
 8 5 2


second array


 9 8 7
 6 5 4


array([[ 9, 24, 56],
       [48, 25,  8]])

In [ ]:
x = np.array([[3,4],[5,6]])
y = np.array([[1,2],[2,1]])

In [ ]:
# 2x3 배열 reshape? 으로 생성후 input값을 넣어주고, 곱해주면 될 듯

In [ ]:
x = np.arange(12).reshape(3, 4) # 12크기의 3x4
print(x)

In [ ]:
print(np.multiply(x, y))

### 형성평가 10
- 4행 2열의 리스트를 입력받아 첫 번째 줄에는 가로평균, 두 번째 줄에는 세로평균 그리고 세 번째 줄에는 전체평균을 출력하는 프로그램을 작성하시오. (소수점 이하는 버림 한다.)

In [49]:
import numpy as np
# x = np.ndarray(shape=(4,2))

lst = []
for i in range(4):
    scores = list(map(int, input().split()))
    lst.append(scores)

# print(lst)

# lst.size # 8 # 안됨.. lst가 ndarray가 아님

# x = np.lst.reshape(4,2) # 응 안돼..
row_avg = 0
col_avg = 0
total_avg = 0
for j in range(len(lst)):
    sum_lst = sum(lst[j])
    print(sum_lst, end = ' ')
print()

    


 1 3
 4 6
 7 9
 1 5


AttributeError: module 'numpy' has no attribute 'lst'

In [53]:
import numpy as np
# x = np.ndarray(shape=(4,2))

lst = []
for i in range(4):
    scores = list(map(int, input().split()))
    lst.append(scores)
print(np.sum(lst, axis=1))
np.sum(lst, axis=0)

 1 3
 4 6
 7 9
 1 9


[ 4 10 16 10]


array([13, 27])